### PR TITLE
Add type of output to getName function

### PR DESCRIPTION
**Pull request by dbritto-dev**

### CODE REVIEW

**Comment by jsoumelidis** [comment]
Thank you @danilobrinu for your suggestion, but this extension and the examples should remain compatible with php v5.6 which does not support return types. The newline at the end of file is correct though :)

**Comment by dbritto-dev** [comment]
@jsoumelidis for PHP 7.2 and more you need the type if not you get and exception. I'm working in a project using PHP 7.2.11.

**Comment by jsoumelidis** [comment]
You're right. Extension explicitly declares the return type of the function since v7.0.x-dev. So this PR should target branch 7.0.x-dev in order this patch to applied to all 7.x.x-dev and master, of course.

**Comment by jsoumelidis** [comment]
@danilobrinu please also note that if your projects uses php 7.2.x then you should use the `7.2.x-dev` branch of the extension. Branch `master` targets php 7.3 (soon php 7.4) and won't work for 7.2 'cause of some php internal api changes.

**Comment by jsoumelidis** [comment]
See #8

**Pull request closed without merging**
